# Generated by Django 4.2.2 on 2023-06-28 13:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('journal', '0002_review'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Review',
        ),
        migrations.DeleteModel(
            name='Task',
        ),
    ]
